name: Build wheels

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linux:
    # Use your existing self-hosted Linux runner with GPU
    runs-on: perimeter-self-host-linux
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: |
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ha4detr-linux
          path: dist/*.whl

  windows:
    # This assumes you eventually wire this to your EC2/SSM-based builder
    runs-on: windows-latest  # OR your own Windows runner when ready
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: |
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ha4detr-windows
          path: dist/*.whl
